language: node_js
node_js:
  - "11.10.1"
sudo: required
services:
  - docker

before_install:
  - docker build -t pkollarath/docker-react -f Dockerfile.dev .

script:
  - docker run pkollarath/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-399408984356"
  bucket_path: "docker-react"
  on
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"